// This file is auto-generated by parse_quizzes.js. Do not edit manually.
import { CourseQuestion } from './oopCourse';

export const OOP_PARSED_QUESTIONS: Record<string, CourseQuestion[]> = {
  "oop_lesson_1": [
    {
      "id": "oop_lesson_1_q01",
      "lessonId": "oop_lesson_1",
      "question": "Which statement best describes a Java class?",
      "options": [
        "A blueprint used to create objects",
        "A command that immediately runs a program",
        "A value stored only inside main",
        "A replacement for all methods"
      ],
      "correctAnswer": "A blueprint used to create objects",
      "explanation": "A class defines the structure and behavior that objects can have. The other choices are incorrect because a class is not a single command, not just a local value, and does not replace methods.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q02",
      "lessonId": "oop_lesson_1",
      "question": "What is an object in Java?",
      "options": [
        "An instance created from a class",
        "A comment inside a program",
        "A keyword used only for printing",
        "A file extension for Java code"
      ],
      "correctAnswer": "An instance created from a class",
      "explanation": "An object is an actual instance based on a class blueprint. The other options describe comments, unrelated keywords, or files rather than objects.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q03",
      "lessonId": "oop_lesson_1",
      "question": "Which part of a class usually stores object state?",
      "options": [
        "Fields",
        "System.out.println",
        "The file name only",
        "Curly braces only"
      ],
      "correctAnswer": "Fields",
      "explanation": "Fields store values that describe an object's state. Printing, file names, and braces do not by themselves store object-specific data.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q04",
      "lessonId": "oop_lesson_1",
      "question": "Which part of a class defines object behavior?",
      "options": [
        "Methods",
        "Spaces",
        "Package folders only",
        "Semicolons only"
      ],
      "correctAnswer": "Methods",
      "explanation": "Methods define actions an object can perform. Spaces, folders, and semicolons may be part of code formatting or syntax, but they do not represent behavior.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q05",
      "lessonId": "oop_lesson_1",
      "question": "Which keyword is used to create a new object?",
      "options": [
        "new",
        "class",
        "void",
        "static"
      ],
      "correctAnswer": "new",
      "explanation": "The new keyword creates an object from a class. class defines a class, void indicates no return value, and static changes member access rules.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q06",
      "lessonId": "oop_lesson_1",
      "question": "Given Student s1 = new Student();, what is s1?",
      "options": [
        "A reference variable for a Student object",
        "The class itself",
        "A field name",
        "A method body"
      ],
      "correctAnswer": "A reference variable for a Student object",
      "explanation": "s1 is a reference variable that refers to a Student object. It is not the class, a field, or a method body.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q07",
      "lessonId": "oop_lesson_1",
      "question": "Which symbol is commonly used to access an object's fields or methods?",
      "options": [
        "Dot operator .",
        "Hash sign #",
        "Question mark ?",
        "Backslash \\"
      ],
      "correctAnswer": "Dot operator .",
      "explanation": "Java uses the dot operator to access fields and methods through an object reference. The other symbols do not perform this object member access.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q08",
      "lessonId": "oop_lesson_1",
      "question": "Which line correctly assigns a value to an object's field?",
      "options": [
        "s1.name = \"Lia\";",
        "name.Student = \"Lia\";",
        "Student.name(\"Lia\");",
        "new = s1.name;"
      ],
      "correctAnswer": "s1.name = \"Lia\";",
      "explanation": "s1.name = \"Lia\"; uses the object reference and dot operator to assign a field value. The other choices use invalid or incorrect Java syntax.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q09",
      "lessonId": "oop_lesson_1",
      "question": "What does object state refer to?",
      "options": [
        "The current values stored in an object's fields",
        "The color of the code editor",
        "The number of Java files in a folder",
        "The name of the operating system"
      ],
      "correctAnswer": "The current values stored in an object's fields",
      "explanation": "Object state means the values stored in fields at a given time. The other choices are external details and do not describe object data.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q10",
      "lessonId": "oop_lesson_1",
      "question": "What does object behavior refer to?",
      "options": [
        "The methods or actions an object can perform",
        "The keyboard shortcut used to run Java",
        "The size of the monitor",
        "The folder where Java is installed"
      ],
      "correctAnswer": "The methods or actions an object can perform",
      "explanation": "Behavior is represented by methods that perform actions. The other choices are environment details and not object behavior.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_1_q11",
      "lessonId": "oop_lesson_1",
      "question": "What is the output of the following code?",
      "options": [
        "Marco is 18",
        "name is age",
        "Student is 18",
        "Compilation error"
      ],
      "correctAnswer": "Marco is 18",
      "explanation": "The object fields are assigned \"Marco\" and 18, and the method prints those values. The other outputs do not match the assigned field values, and the code is valid.",
      "difficulty": "Medium",
      "codeSnippet": "class Student {\n    String name;\n    int age;\n\n    void introduce() {\n        System.out.println(name + \" is \" + age);\n    }\n}\n\nclass Main {\n    public static void main(String[] args) {\n        Student s = new Student();\n        s.name = \"Marco\";\n        s.age = 18;\n        s.introduce();\n    }\n}"
    },
    {
      "id": "oop_lesson_1_q12",
      "lessonId": "oop_lesson_1",
      "question": "Which line creates the object in this code?",
      "options": [
        "s = new Student();",
        "s.name = \"Jade\";",
        "Student s;",
        "All three lines create objects"
      ],
      "correctAnswer": "s = new Student();",
      "explanation": "new Student() creates the actual object. Student s; only declares a reference, while s.name = \"Jade\"; assigns a field.",
      "difficulty": "Medium",
      "codeSnippet": "Student s;\ns = new Student();\ns.name = \"Jade\";"
    },
    {
      "id": "oop_lesson_1_q13",
      "lessonId": "oop_lesson_1",
      "question": "Which statement is correct about two objects created from the same class?",
      "options": [
        "They can store different values in their own fields.",
        "They must always store identical field values.",
        "Only the first object can call methods.",
        "The second object deletes the first object automatically."
      ],
      "correctAnswer": "They can store different values in their own fields.",
      "explanation": "Objects from the same class share structure but can have different state. The other choices incorrectly limit object behavior or describe automatic deletion that does not occur.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_1_q14",
      "lessonId": "oop_lesson_1",
      "question": "What is wrong with this code?",
      "options": [
        "The object was not created before using p.name.",
        "The class name must be lowercase.",
        "The field must be declared inside main.",
        "Java does not allow String fields."
      ],
      "correctAnswer": "The object was not created before using p.name.",
      "explanation": "Product p; declares only a reference, so p does not refer to an object yet. The code needs p = new Product(); before accessing p.name.",
      "difficulty": "Medium",
      "codeSnippet": "class Product {\n    String name;\n}\n\nclass Main {\n    public static void main(String[] args) {\n        Product p;\n        p.name = \"Keyboard\";\n    }\n}"
    },
    {
      "id": "oop_lesson_1_q15",
      "lessonId": "oop_lesson_1",
      "question": "Which replacement correctly completes the code?",
      "options": [
        "new Phone()",
        "Phone;",
        "\"Phone\"",
        "brand.Phone()"
      ],
      "correctAnswer": "new Phone()",
      "explanation": "new Phone() constructs a new Phone object. The other choices do not create a valid object instance.",
      "difficulty": "Medium",
      "codeSnippet": "class Phone {\n    String brand;\n}\n\nclass Main {\n    public static void main(String[] args) {\n        Phone p = ________;\n        p.brand = \"Nova\";\n    }\n}"
    },
    {
      "id": "oop_lesson_1_q16",
      "lessonId": "oop_lesson_1",
      "question": "What is the output?",
      "options": [
        "Red",
        "Blue",
        "Blue Red",
        "Compilation error"
      ],
      "correctAnswer": "Red",
      "explanation": "The method is called on b2, whose color field is \"Red\". b1 has a separate state, so its \"Blue\" value is not printed.",
      "difficulty": "Medium",
      "codeSnippet": "class Bag {\n    String color;\n\n    void showColor() {\n        System.out.println(color);\n    }\n}\n\nclass Main {\n    public static void main(String[] args) {\n        Bag b1 = new Bag();\n        Bag b2 = new Bag();\n        b1.color = \"Blue\";\n        b2.color = \"Red\";\n        b2.showColor();\n    }\n}"
    },
    {
      "id": "oop_lesson_1_q17",
      "lessonId": "oop_lesson_1",
      "question": "Which statement best explains why classes help organize code?",
      "options": [
        "They group related data and behavior into one structure.",
        "They remove the need to compile Java code.",
        "They force every program to have only one object.",
        "They prevent methods from being written."
      ],
      "correctAnswer": "They group related data and behavior into one structure.",
      "explanation": "Classes organize related fields and methods. The other choices are false because Java code still compiles, programs can have many objects, and classes commonly contain methods.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_1_q18",
      "lessonId": "oop_lesson_1",
      "question": "What should replace the missing code to call the method?",
      "options": [
        "lamp.turnOn();",
        "Light.turnOn;",
        "turnOn.lamp();",
        "new turnOn();"
      ],
      "correctAnswer": "lamp.turnOn();",
      "explanation": "lamp.turnOn(); calls the instance method using the object reference. The other choices use invalid or incorrect method-call syntax.",
      "difficulty": "Medium",
      "codeSnippet": "class Light {\n    void turnOn() {\n        System.out.println(\"Light on\");\n    }\n}\n\nclass Main {\n    public static void main(String[] args) {\n        Light lamp = new Light();\n        ________;\n    }\n}"
    },
    {
      "id": "oop_lesson_1_q19",
      "lessonId": "oop_lesson_1",
      "question": "Which code best models a real-world student as an object?",
      "options": [
        "class Student { String name; int age; }",
        "int Student = 5;",
        "System.out.println(\"Student\");",
        "if (student) { }"
      ],
      "correctAnswer": "class Student { String name; int age; }",
      "explanation": "A class with fields can model a student's data. The other choices do not define a reusable object structure.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_1_q20",
      "lessonId": "oop_lesson_1",
      "question": "What is the output?",
      "options": [
        "4",
        "0",
        "3",
        "Compilation error"
      ],
      "correctAnswer": "4",
      "explanation": "The field starts at 3, then increase() adds one. The final printed value is therefore 4.",
      "difficulty": "Medium",
      "codeSnippet": "class Counter {\n    int value;\n\n    void increase() {\n        value++;\n    }\n}\n\nclass Main {\n    public static void main(String[] args) {\n        Counter c = new Counter();\n        c.value = 3;\n        c.increase();\n        System.out.println(c.value);\n    }\n}"
    },
    {
      "id": "oop_lesson_1_q21",
      "lessonId": "oop_lesson_1",
      "question": "A school management system needs to store each student's name and age and allow each student to introduce themselves. Which design is most appropriate?",
      "options": [
        "Create a Student class with fields and an introduce() method.",
        "Store all student data in one long String.",
        "Use only System.out.println() statements without objects.",
        "Use a separate Java file for every student name only."
      ],
      "correctAnswer": "Create a Student class with fields and an introduce() method.",
      "explanation": "A Student class groups the object's state and behavior clearly. The other choices make the program harder to reuse, organize, or extend.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_1_q22",
      "lessonId": "oop_lesson_1",
      "question": "What is the main design problem in this code?",
      "options": [
        "It uses variables but does not model related entities as classes.",
        "It has too many classes.",
        "It creates too many objects.",
        "It uses fields incorrectly inside a class."
      ],
      "correctAnswer": "It uses variables but does not model related entities as classes.",
      "explanation": "The data is related to real-world entities, but it is stored as separate local variables. Classes could organize this state more clearly into objects such as Student and Teacher.",
      "difficulty": "Hard",
      "codeSnippet": "class Main {\n    public static void main(String[] args) {\n        String studentName = \"Nina\";\n        int studentAge = 19;\n        String teacherName = \"Mr. Cruz\";\n        int teacherAge = 35;\n    }\n}"
    },
    {
      "id": "oop_lesson_1_q23",
      "lessonId": "oop_lesson_1",
      "question": "Why is s1.name and s2.name able to hold different values when s1 and s2 are both Student objects?",
      "options": [
        "Each object has its own copy of instance fields.",
        "Java randomly chooses a name for each object.",
        "The class is duplicated in the source file.",
        "Methods erase fields after each call."
      ],
      "correctAnswer": "Each object has its own copy of instance fields.",
      "explanation": "Each object has separate instance field values. The other choices describe behavior that does not happen in Java.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_1_q24",
      "lessonId": "oop_lesson_1",
      "question": "Which code shows the best use of object behavior instead of doing everything directly in main?",
      "options": [
        "Student s = new Student(); s.name = \"Ana\"; s.age = 20; s.introduce();",
        "System.out.println(\"Ana is 20\");",
        "String data = \"Ana,20\";",
        "int age = 20; System.out.println(age);"
      ],
      "correctAnswer": "Student s = new Student(); s.name = \"Ana\"; s.age = 20; s.introduce();",
      "explanation": "This code creates an object, assigns state, and calls a method that represents behavior. The other choices print or store values without modeling behavior through an object.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_1_q25",
      "lessonId": "oop_lesson_1",
      "question": "A beginner writes Student s = null; s.introduce();. What is the best explanation?",
      "options": [
        "It is unsafe because s does not refer to an actual object.",
        "It works because null automatically creates an object.",
        "It prints the default student values.",
        "It creates two Student objects."
      ],
      "correctAnswer": "It is unsafe because s does not refer to an actual object.",
      "explanation": "null means the reference does not point to an object, so calling a method through it is invalid at runtime. The other choices incorrectly assume an object is created or usable.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_2": [
    {
      "id": "oop_lesson_2_q01",
      "lessonId": "oop_lesson_2",
      "question": "What is the primary purpose of a constructor in Java?",
      "options": [
        "To delete an object",
        "To initialize an object when it is created",
        "To define a method",
        "To terminate a program"
      ],
      "correctAnswer": "To initialize an object when it is created",
      "explanation": "\"To initialize an object when it is created\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_2_q02",
      "lessonId": "oop_lesson_2",
      "question": "What is a constructor?",
      "options": [
        "A special variable",
        "A special method used to initialize objects",
        "A package",
        "A Java keyword"
      ],
      "correctAnswer": "A special method used to initialize objects",
      "explanation": "\"A special method used to initialize objects\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_2_q03",
      "lessonId": "oop_lesson_2",
      "question": "Which statement about constructors is TRUE?",
      "options": [
        "Constructors have a return type.",
        "Constructors must return an object.",
        "Constructors have the same name as the class.",
        "Constructors can only be private."
      ],
      "correctAnswer": "Constructors have the same name as the class.",
      "explanation": "\"Constructors have the same name as the class.\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_2_q04",
      "lessonId": "oop_lesson_2",
      "question": "Which of the following is the correct constructor declaration?",
      "options": [
        "void Student(){}",
        "Student(){}",
        "constructor Student(){}",
        "new Student(){}"
      ],
      "correctAnswer": "Student(){}",
      "explanation": "\"Student(){}\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Easy",
      "codeSnippet": "class Student{\n    __________\n}"
    },
    {
      "id": "oop_lesson_2_q05",
      "lessonId": "oop_lesson_2",
      "question": "Which statement automatically calls a constructor?",
      "options": [
        "Student();",
        "Student s;",
        "Student s = new Student();",
        "new();"
      ],
      "correctAnswer": "Student s = new Student();",
      "explanation": "\"Student s = new Student();\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_2_q06",
      "lessonId": "oop_lesson_2",
      "question": "Which keyword invokes a constructor?",
      "options": [
        "class",
        "new",
        "public",
        "static"
      ],
      "correctAnswer": "new",
      "explanation": "\"new\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_2_q07",
      "lessonId": "oop_lesson_2",
      "question": ". How many times is the constructor executed?",
      "options": [
        "One",
        "Two",
        "Three",
        "None"
      ],
      "correctAnswer": "Two",
      "explanation": "\"Two\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "class Car{\n    Car(){\n        System.out.println(\"New Car\");\n    }\n}\nCar c1 = new Car();\nCar c2 = new Car();"
    },
    {
      "id": "oop_lesson_2_q08",
      "lessonId": "oop_lesson_2",
      "question": "Which of the following is NOT true about constructors?",
      "options": [
        "They initialize objects.",
        "They have the same name as the class.",
        "They can be overloaded.",
        "They return integers."
      ],
      "correctAnswer": "They return integers.",
      "explanation": "\"They return integers.\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_2_q09",
      "lessonId": "oop_lesson_2",
      "question": "What happens when this code executes?",
      "options": [
        "The constructor is automatically called.",
        "Nothing happens.",
        "The class is deleted.",
        "The method is ignored."
      ],
      "correctAnswer": "The constructor is automatically called.",
      "explanation": "\"The constructor is automatically called.\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "Student s = new Student();"
    },
    {
      "id": "oop_lesson_2_q10",
      "lessonId": "oop_lesson_2",
      "question": "Which constructor is created automatically by Java if no constructor exists?",
      "options": [
        "Copy Constructor",
        "Default Constructor",
        "Parameterized Constructor",
        "Abstract Constructor"
      ],
      "correctAnswer": "Default Constructor",
      "explanation": "\"Default Constructor\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_2_q11",
      "lessonId": "oop_lesson_2",
      "question": "Which constructor initializes an object's values during creation?",
      "options": [
        "Empty Constructor",
        "Parameterized Constructor",
        "Package Constructor",
        "Static Constructor"
      ],
      "correctAnswer": "Parameterized Constructor",
      "explanation": "\"Parameterized Constructor\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_2_q12",
      "lessonId": "oop_lesson_2",
      "question": "A developer wants every Employee object to have a name immediately after it is created. Which constructor should be used?",
      "options": [
        "Default Constructor",
        "Parameterized Constructor",
        "Abstract Constructor",
        "Static Constructor"
      ],
      "correctAnswer": "Parameterized Constructor",
      "explanation": "\"Parameterized Constructor\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_2_q13",
      "lessonId": "oop_lesson_2",
      "question": "Which code creates an object using a parameterized constructor?",
      "options": [
        "Student s = new Student();",
        "Student s = Student(\"John\");",
        "Student s = new Student(\"John\");",
        "Student(\"John\");"
      ],
      "correctAnswer": "Student s = new Student(\"John\");",
      "explanation": "\"Student s = new Student(\"John\");\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_2_q14",
      "lessonId": "oop_lesson_2",
      "question": "Why are constructors useful?",
      "options": [
        "They automatically initialize object data.",
        "They reduce the number of classes.",
        "They replace packages.",
        "They prevent object creation."
      ],
      "correctAnswer": "They automatically initialize object data.",
      "explanation": "\"They automatically initialize object data.\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_2_q15",
      "lessonId": "oop_lesson_2",
      "question": "Which statement best explains the role of constructors in object-oriented programming?",
      "options": [
        "Constructors are used to destroy objects.",
        "Constructors ensure that newly created objects start with an initialized state.",
        "Constructors define inheritance relationships.",
        "Constructors replace methods."
      ],
      "correctAnswer": "Constructors ensure that newly created objects start with an initialized state.",
      "explanation": "\"Constructors ensure that newly created objects start with an initialized state.\" is the correct answer based on Topic 2 concepts.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_3": [
    {
      "id": "oop_lesson_3_q01",
      "lessonId": "oop_lesson_3",
      "question": "What is an object method in Java?",
      "options": [
        "A variable inside a class",
        "A function that belongs to an object or class",
        "A package in Java",
        "A constructor"
      ],
      "correctAnswer": "A function that belongs to an object or class",
      "explanation": "\"A function that belongs to an object or class\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_3_q02",
      "lessonId": "oop_lesson_3",
      "question": "Which keyword is commonly used to define a method's access level?",
      "options": [
        "class",
        "public",
        "object",
        "new"
      ],
      "correctAnswer": "public",
      "explanation": "\"public\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_3_q03",
      "lessonId": "oop_lesson_3",
      "question": "Which of the following is a correctly declared method?",
      "options": [
        "void display() {\n}",
        "display() {\n}",
        "method display() {\n}",
        "public display {\n}"
      ],
      "correctAnswer": "void display() {\n}",
      "explanation": "\"void display() {\n}\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_3_q04",
      "lessonId": "oop_lesson_3",
      "question": "Which statement correctly calls the method display() of an object named student?",
      "options": [
        "student.display();",
        "display.student();",
        "display(student);",
        "student->display();"
      ],
      "correctAnswer": "student.display();",
      "explanation": "\"student.display();\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_3_q05",
      "lessonId": "oop_lesson_3",
      "question": "Consider the code: What is the output?",
      "options": [
        "Student",
        "Welcome!",
        "null",
        "Compilation Error"
      ],
      "correctAnswer": "Welcome!",
      "explanation": "\"Welcome!\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Easy",
      "codeSnippet": "class Student{\n    void greet(){\n        System.out.println(\"Welcome!\");\n    }\n}\npublic class Main{\n    public static void main(String[] args){\n        Student s = new Student();\n        s.greet();\n    }\n}"
    },
    {
      "id": "oop_lesson_3_q06",
      "lessonId": "oop_lesson_3",
      "question": "Which code correctly calls a method with one parameter?",
      "options": [
        "display();",
        "display(\"John\");",
        "display;",
        "display = \"John\";"
      ],
      "correctAnswer": "display(\"John\");",
      "explanation": "\"display(\"John\");\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_3_q07",
      "lessonId": "oop_lesson_3",
      "question": "What is the output?",
      "options": [
        "Hello Alice",
        "Alice Hello",
        "Hello",
        "Error"
      ],
      "correctAnswer": "Hello Alice",
      "explanation": "\"Hello Alice\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "class Student{\n    void greet(String name){\n        System.out.println(\"Hello \" + name);\n    }\n}\npublic class Main{\n    public static void main(String[] args){\n        Student s = new Student();\n        s.greet(\"Alice\");\n    }\n}"
    },
    {
      "id": "oop_lesson_3_q08",
      "lessonId": "oop_lesson_3",
      "question": "Which statement about return values is TRUE?",
      "options": [
        "Every method must return a value.",
        "Only constructors return values.",
        "Methods with void do not return a value.",
        "Return values are optional for int methods."
      ],
      "correctAnswer": "Methods with void do not return a value.",
      "explanation": "\"Methods with void do not return a value.\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_3_q09",
      "lessonId": "oop_lesson_3",
      "question": "Which keyword returns a value from a method?",
      "options": [
        "output",
        "send",
        "return",
        "give"
      ],
      "correctAnswer": "return",
      "explanation": "\"return\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_3_q10",
      "lessonId": "oop_lesson_3",
      "question": "Which of the following methods accepts two integer parameters?",
      "options": [
        "void add(int a, int b)",
        "void add()",
        "int add",
        "method add(int a)"
      ],
      "correctAnswer": "void add(int a, int b)",
      "explanation": "\"void add(int a, int b)\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_3_q11",
      "lessonId": "oop_lesson_3",
      "question": "Which method would most likely return a student's average grade?",
      "options": [
        "void average()",
        "double average()",
        "Student average()",
        "public average"
      ],
      "correctAnswer": "double average()",
      "explanation": "\"double average()\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_3_q12",
      "lessonId": "oop_lesson_3",
      "question": "What happens if a void method is called?",
      "options": [
        "It returns an integer.",
        "It performs its task without returning a value.",
        "It creates an object.",
        "It becomes a constructor."
      ],
      "correctAnswer": "It performs its task without returning a value.",
      "explanation": "\"It performs its task without returning a value.\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_3_q13",
      "lessonId": "oop_lesson_3",
      "question": "Which code correctly calls the method calculate() of an object named calc?",
      "options": [
        "calc.calculate();",
        "calculate.calc();",
        "calculate();",
        "calc->calculate();"
      ],
      "correctAnswer": "calc.calculate();",
      "explanation": "\"calc.calculate();\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_3_q14",
      "lessonId": "oop_lesson_3",
      "question": "Which statement best describes methods in Object-Oriented Programming?",
      "options": [
        "Methods describe an object's behavior.",
        "Methods replace objects.",
        "Methods create packages.",
        "Methods store object references."
      ],
      "correctAnswer": "Methods describe an object's behavior.",
      "explanation": "\"Methods describe an object's behavior.\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_3_q15",
      "lessonId": "oop_lesson_3",
      "question": "A Car object contains the methods start(), stop(), and accelerate(). These methods represent the car's:",
      "options": [
        "State",
        "Behavior",
        "Constructor",
        "Attributes"
      ],
      "correctAnswer": "Behavior",
      "explanation": "\"Behavior\" is the correct answer based on Topic 3 concepts.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_4": [
    {
      "id": "oop_lesson_4_q01",
      "lessonId": "oop_lesson_4",
      "question": "What is encapsulation in Java?",
      "options": [
        "Combining data and methods into a single unit while restricting direct access to data",
        "Creating multiple objects from one class",
        "Writing several methods with the same name",
        "Creating abstract classes"
      ],
      "correctAnswer": "Combining data and methods into a single unit while restricting direct access to data",
      "explanation": "\"Combining data and methods into a single unit while restricting direct access to data\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_4_q02",
      "lessonId": "oop_lesson_4",
      "question": "Which access modifier is commonly used to achieve encapsulation?",
      "options": [
        "public",
        "protected",
        "private",
        "static"
      ],
      "correctAnswer": "private",
      "explanation": "\"private\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_4_q03",
      "lessonId": "oop_lesson_4",
      "question": "Why are instance variables often declared as private?",
      "options": [
        "To make them accessible from anywhere",
        "To hide data and prevent unauthorized access",
        "To improve program speed",
        "To allow inheritance"
      ],
      "correctAnswer": "To hide data and prevent unauthorized access",
      "explanation": "\"To hide data and prevent unauthorized access\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_4_q04",
      "lessonId": "oop_lesson_4",
      "question": "Which method is used to retrieve the value of a private field?",
      "options": [
        "Setter",
        "Getter",
        "Constructor",
        "Destructor"
      ],
      "correctAnswer": "Getter",
      "explanation": "\"Getter\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_4_q05",
      "lessonId": "oop_lesson_4",
      "question": "Which method is used to modify the value of a private field?",
      "options": [
        "Getter",
        "Setter",
        "Main Method",
        "Static Method"
      ],
      "correctAnswer": "Setter",
      "explanation": "\"Setter\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_4_q06",
      "lessonId": "oop_lesson_4",
      "question": "What happens if you try to access a private variable directly from another class?",
      "options": [
        "The program runs successfully.",
        "A compilation error occurs.",
        "The variable becomes public.",
        "Java automatically creates a getter."
      ],
      "correctAnswer": "A compilation error occurs.",
      "explanation": "\"A compilation error occurs.\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_4_q07",
      "lessonId": "oop_lesson_4",
      "question": "Which of the following demonstrates encapsulation?",
      "options": [
        "public int age;",
        "private int age;\n\npublic int getAge(){\n    return age;\n}",
        "int age;",
        "protected int age;"
      ],
      "correctAnswer": "private int age;\n\npublic int getAge(){\n    return age;\n}",
      "explanation": "\"private int age;\n\npublic int getAge(){\n    return age;\n}\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_4_q08",
      "lessonId": "oop_lesson_4",
      "question": "Why is encapsulation considered a security feature?",
      "options": [
        "It encrypts data.",
        "It controls how data is accessed and modified.",
        "It prevents object creation.",
        "It deletes unused variables."
      ],
      "correctAnswer": "It controls how data is accessed and modified.",
      "explanation": "\"It controls how data is accessed and modified.\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_4_q09",
      "lessonId": "oop_lesson_4",
      "question": "What keyword refers to the current object's instance variable inside a setter?",
      "options": [
        "super",
        "this",
        "self",
        "object"
      ],
      "correctAnswer": "this",
      "explanation": "\"this\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_4_q10",
      "lessonId": "oop_lesson_4",
      "question": "What is the output?",
      "options": [
        "50000",
        "salary",
        "null",
        "Error"
      ],
      "correctAnswer": "50000",
      "explanation": "\"50000\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "class Employee{\n    private double salary = 50000;\n    public double getSalary(){\n        return salary;\n    }\n}\npublic class Main{\n    public static void main(String[] args){\n        Employee emp = new Employee();\n        System.out.println(emp.getSalary());\n    }\n}"
    },
    {
      "id": "oop_lesson_4_q11",
      "lessonId": "oop_lesson_4",
      "question": "Which code prevents invalid values from being assigned?",
      "options": [
        "public void setAge(int age){\n    this.age = age;\n}",
        "public void setAge(int age){\n    if(age >= 0){\n        this.age = age;\n    }\n}",
        "public int age;",
        "age = input;"
      ],
      "correctAnswer": "public void setAge(int age){\n    if(age >= 0){\n        this.age = age;\n    }\n}",
      "explanation": "\"public void setAge(int age){\n    if(age >= 0){\n        this.age = age;\n    }\n}\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_4_q12",
      "lessonId": "oop_lesson_4",
      "question": "What is the output?",
      "options": [
        "Manila",
        "Person",
        "null",
        "Error"
      ],
      "correctAnswer": "Manila",
      "explanation": "\"Manila\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Hard",
      "codeSnippet": "class Person{\n    private String city = \"Manila\";\n    public String getCity(){\n        return city;\n    }\n}\npublic class Main{\n    public static void main(String[] args){\n        Person p = new Person();\n        System.out.println(p.getCity());\n    }\n}"
    },
    {
      "id": "oop_lesson_4_q13",
      "lessonId": "oop_lesson_4",
      "question": "Which statement best describes a setter method?",
      "options": [
        "It returns the value of a variable.",
        "It updates the value of a private variable.",
        "It creates a new object.",
        "It deletes a variable."
      ],
      "correctAnswer": "It updates the value of a private variable.",
      "explanation": "\"It updates the value of a private variable.\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_4_q14",
      "lessonId": "oop_lesson_4",
      "question": "Why is direct access to object data generally discouraged?",
      "options": [
        "It increases program size.",
        "It can lead to invalid or inconsistent object states.",
        "It slows down Java.",
        "It prevents inheritance."
      ],
      "correctAnswer": "It can lead to invalid or inconsistent object states.",
      "explanation": "\"It can lead to invalid or inconsistent object states.\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_4_q15",
      "lessonId": "oop_lesson_4",
      "question": "A developer wants to ensure that a student's grade is always between 0 and 100. Where should this validation be placed?",
      "options": [
        "In the getter method",
        "In the setter method",
        "In the main() method",
        "In a package"
      ],
      "correctAnswer": "In the setter method",
      "explanation": "\"In the setter method\" is the correct answer based on Topic 4 concepts.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_5": [
    {
      "id": "oop_lesson_5_q01",
      "lessonId": "oop_lesson_5",
      "question": "What is constructor overloading in Java?",
      "options": [
        "Creating multiple classes with the same name",
        "Creating multiple constructors with different parameter lists in the same class",
        "Creating multiple methods with different return types only",
        "Creating multiple objects using one constructor"
      ],
      "correctAnswer": "Creating multiple constructors with different parameter lists in the same class",
      "explanation": "\"Creating multiple constructors with different parameter lists in the same class\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_5_q02",
      "lessonId": "oop_lesson_5",
      "question": "Which statement is TRUE about overloaded constructors?",
      "options": [
        "They must have different names.",
        "They must have different parameter lists.",
        "They must have different return types.",
        "They must be declared as static."
      ],
      "correctAnswer": "They must have different parameter lists.",
      "explanation": "\"They must have different parameter lists.\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_5_q03",
      "lessonId": "oop_lesson_5",
      "question": "Which of the following is a valid example of constructor overloading?",
      "options": [
        "Student(){}\nStudent(String name){}\nStudent(String name, int age){}",
        "Student(){}\nStudent(){}",
        "void Student(){}\nStudent(){}",
        "Student(int id){}\nStudent(int id){}"
      ],
      "correctAnswer": "Student(){}\nStudent(String name){}\nStudent(String name, int age){}",
      "explanation": "\"Student(){}\nStudent(String name){}\nStudent(String name, int age){}\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_5_q04",
      "lessonId": "oop_lesson_5",
      "question": "Why is constructor overloading useful?",
      "options": [
        "It allows objects to be initialized in different ways.",
        "It makes all variables public.",
        "It prevents object creation.",
        "It replaces inheritance."
      ],
      "correctAnswer": "It allows objects to be initialized in different ways.",
      "explanation": "\"It allows objects to be initialized in different ways.\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_5_q05",
      "lessonId": "oop_lesson_5",
      "question": "Which constructor is called?",
      "options": [
        "Parameterized constructor",
        "Default (no-argument) constructor",
        "Copy constructor",
        "Static constructor"
      ],
      "correctAnswer": "Default (no-argument) constructor",
      "explanation": "\"Default (no-argument) constructor\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Easy",
      "codeSnippet": "Student s = new Student();"
    },
    {
      "id": "oop_lesson_5_q06",
      "lessonId": "oop_lesson_5",
      "question": "Which of the following is NOT part of a constructor's signature?",
      "options": [
        "Number of parameters",
        "Data types of parameters",
        "Order of parameters",
        "Return type"
      ],
      "correctAnswer": "Return type",
      "explanation": "\"Return type\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_5_q07",
      "lessonId": "oop_lesson_5",
      "question": "What is the output?",
      "options": [
        "Book",
        "title",
        "null",
        "Error"
      ],
      "correctAnswer": "Book",
      "explanation": "\"Book\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "class Book{\n    Book(){\n        System.out.println(\"Book\");\n    }\n    Book(String title){\n        System.out.println(title);\n    }\n}\npublic class Main{\n    public static void main(String[] args){\n        new Book();\n    }\n}"
    },
    {
      "id": "oop_lesson_5_q08",
      "lessonId": "oop_lesson_5",
      "question": "Which code creates an object using the constructor with two parameters?",
      "options": [
        "new Student();",
        "new Student(\"John\");",
        "new Student(\"John\",20);",
        "Student();"
      ],
      "correctAnswer": "new Student(\"John\",20);",
      "explanation": "\"new Student(\"John\",20);\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_5_q09",
      "lessonId": "oop_lesson_5",
      "question": "Which statement is FALSE?",
      "options": [
        "Constructors can be overloaded.",
        "Overloaded constructors have different parameter lists.",
        "Constructors can have different names.",
        "Java chooses the constructor based on the arguments provided."
      ],
      "correctAnswer": "Constructors can have different names.",
      "explanation": "\"Constructors can have different names.\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_5_q10",
      "lessonId": "oop_lesson_5",
      "question": "Which of the following is a valid overloaded constructor?",
      "options": [
        "Car(){}\nCar(int year){}",
        "Car(){}\nvoid Car(){}",
        "Car(int year){}\nCar(int year){}",
        "void Car(int year){}"
      ],
      "correctAnswer": "Car(){}\nCar(int year){}",
      "explanation": "\"Car(){}\nCar(int year){}\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_5_q11",
      "lessonId": "oop_lesson_5",
      "question": "Which constructor is selected?",
      "options": [
        "Book()",
        "Book(String title)",
        "Book(int pages)",
        "Book(double price)"
      ],
      "correctAnswer": "Book(int pages)",
      "explanation": "\"Book(int pages)\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Hard",
      "codeSnippet": "new Book(250);"
    },
    {
      "id": "oop_lesson_5_q12",
      "lessonId": "oop_lesson_5",
      "question": "Why can't constructors be overloaded using only different return types?",
      "options": [
        "Constructors do not have return types.",
        "Java ignores return types.",
        "Constructors are methods.",
        "Return types determine constructor names."
      ],
      "correctAnswer": "Constructors do not have return types.",
      "explanation": "\"Constructors do not have return types.\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_5_q13",
      "lessonId": "oop_lesson_5",
      "question": "Which statement correctly explains how Java chooses an overloaded constructor?",
      "options": [
        "By alphabetical order.",
        "By matching the argument list with the constructor parameters.",
        "By the constructor's access modifier.",
        "Randomly."
      ],
      "correctAnswer": "By matching the argument list with the constructor parameters.",
      "explanation": "\"By matching the argument list with the constructor parameters.\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_5_q14",
      "lessonId": "oop_lesson_5",
      "question": "Which constructor will execute?",
      "options": [
        "A",
        "B",
        "AB",
        "Error"
      ],
      "correctAnswer": "A",
      "explanation": "\"A\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Hard",
      "codeSnippet": "class Car{\n    Car(){\n        System.out.println(\"A\");\n    }\n    Car(String brand){\n        System.out.println(\"B\");\n    }\n}\nCar c = new Car();"
    },
    {
      "id": "oop_lesson_5_q15",
      "lessonId": "oop_lesson_5",
      "question": "A developer wants users to create a Rectangle object in two ways: Without dimensions (default size) With width and height Which feature should be used?",
      "options": [
        "Method Overriding",
        "Constructor Overloading",
        "Encapsulation",
        "Inheritance"
      ],
      "correctAnswer": "Constructor Overloading",
      "explanation": "\"Constructor Overloading\" is the correct answer based on Topic 5 concepts.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_6": [
    {
      "id": "oop_lesson_6_q01",
      "lessonId": "oop_lesson_6",
      "question": "What is inheritance in Java?",
      "options": [
        "A way to create multiple constructors",
        "A mechanism that allows one class to acquire the properties and methods of another class",
        "A method for hiding data",
        "A way to overload methods"
      ],
      "correctAnswer": "A mechanism that allows one class to acquire the properties and methods of another class",
      "explanation": "\"A mechanism that allows one class to acquire the properties and methods of another class\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_6_q02",
      "lessonId": "oop_lesson_6",
      "question": "Which keyword is used to inherit a class in Java?",
      "options": [
        "inherit",
        "implements",
        "extends",
        "super"
      ],
      "correctAnswer": "extends",
      "explanation": "\"extends\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_6_q03",
      "lessonId": "oop_lesson_6",
      "question": "In inheritance, the class being inherited is called the:",
      "options": [
        "Child Class",
        "Derived Class",
        "Parent (Superclass)",
        "Object Class"
      ],
      "correctAnswer": "Parent (Superclass)",
      "explanation": "\"Parent (Superclass)\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_6_q04",
      "lessonId": "oop_lesson_6",
      "question": "The class that inherits from another class is called the:",
      "options": [
        "Parent Class",
        "Child (Subclass)",
        "Main Class",
        "Static Class"
      ],
      "correctAnswer": "Child (Subclass)",
      "explanation": "\"Child (Subclass)\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_6_q05",
      "lessonId": "oop_lesson_6",
      "question": "Which of the following correctly creates an inheritance relationship?",
      "options": [
        "class Dog inherits Animal { }",
        "class Dog extends Animal { }",
        "class Dog implements Animal { }",
        "class Dog super Animal { }"
      ],
      "correctAnswer": "class Dog extends Animal { }",
      "explanation": "\"class Dog extends Animal { }\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_6_q06",
      "lessonId": "oop_lesson_6",
      "question": "Which keyword calls the parent class constructor?",
      "options": [
        "this()",
        "super()",
        "extends()",
        "parent()"
      ],
      "correctAnswer": "super()",
      "explanation": "\"super()\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_6_q07",
      "lessonId": "oop_lesson_6",
      "question": "What happens if a child class constructor does not explicitly call super()?",
      "options": [
        "Compilation Error",
        "Java automatically calls the parent's no-argument constructor.",
        "The child constructor is ignored.",
        "Nothing happens."
      ],
      "correctAnswer": "Java automatically calls the parent's no-argument constructor.",
      "explanation": "\"Java automatically calls the parent's no-argument constructor.\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_6_q08",
      "lessonId": "oop_lesson_6",
      "question": "What is the output?",
      "options": [
        "Dog\nAnimal",
        "Animal\nDog",
        "Dog",
        "Error"
      ],
      "correctAnswer": "Animal\nDog",
      "explanation": "\"Animal\nDog\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "class Animal{\n    Animal(){\n        System.out.println(\"Animal\");\n    }\n}\nclass Dog extends Animal{\n    Dog(){\n        System.out.println(\"Dog\");\n    }\n}\npublic class Main{\n    public static void main(String[] args){\n        new Dog();\n    }\n}"
    },
    {
      "id": "oop_lesson_6_q09",
      "lessonId": "oop_lesson_6",
      "question": "Which statement about constructors and inheritance is TRUE?",
      "options": [
        "Constructors are inherited.",
        "Parent constructors can be called using super().",
        "Constructors are overridden.",
        "Constructors are private by default."
      ],
      "correctAnswer": "Parent constructors can be called using super().",
      "explanation": "\"Parent constructors can be called using super().\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_6_q10",
      "lessonId": "oop_lesson_6",
      "question": "What will super.display(); do?",
      "options": [
        "Call the child class method.",
        "Call the parent class method.",
        "Create an object.",
        "Override a method."
      ],
      "correctAnswer": "Call the parent class method.",
      "explanation": "\"Call the parent class method.\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_6_q11",
      "lessonId": "oop_lesson_6",
      "question": "Which keyword refers to the current object?",
      "options": [
        "parent",
        "super",
        "this",
        "extends"
      ],
      "correctAnswer": "this",
      "explanation": "\"this\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_6_q12",
      "lessonId": "oop_lesson_6",
      "question": "Which statement correctly distinguishes this and super?",
      "options": [
        "Both always refer to the current object.",
        "this refers to the current object, while super refers to the parent class.",
        "super creates objects.",
        "They are identical."
      ],
      "correctAnswer": "this refers to the current object, while super refers to the parent class.",
      "explanation": "\"this refers to the current object, while super refers to the parent class.\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_6_q13",
      "lessonId": "oop_lesson_6",
      "question": "What is the output of the code?",
      "options": [
        "SavingsAccount is the parent class.",
        "Account inherits from SavingsAccount.",
        "SavingsAccount is the child class.",
        "The classes are unrelated."
      ],
      "correctAnswer": "SavingsAccount is the child class.",
      "explanation": "\"SavingsAccount is the child class.\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Hard",
      "codeSnippet": "A SavingsAccount class extends an Account class. What is the relationship?"
    },
    {
      "id": "oop_lesson_6_q14",
      "lessonId": "oop_lesson_6",
      "question": "Which code correctly calls a parent constructor with one parameter?",
      "options": [
        "super(name);",
        "this(name);",
        "parent(name);",
        "extends(name);"
      ],
      "correctAnswer": "super(name);",
      "explanation": "\"super(name);\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_6_q15",
      "lessonId": "oop_lesson_6",
      "question": "A Teacher class and a Student class both share common attributes such as name and age. What is the BEST design?",
      "options": [
        "Duplicate the variables in both classes.",
        "Create a Person parent class and let both classes extend it.",
        "Use only interfaces.",
        "Store everything in the main() method."
      ],
      "correctAnswer": "Create a Person parent class and let both classes extend it.",
      "explanation": "\"Create a Person parent class and let both classes extend it.\" is the correct answer based on Topic 6 concepts.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_7": [
    {
      "id": "oop_lesson_7_q01",
      "lessonId": "oop_lesson_7",
      "question": "What is polymorphism in Java?",
      "options": [
        "The ability of one object to take many forms",
        "The process of hiding data",
        "Creating multiple constructors",
        "Declaring private variables"
      ],
      "correctAnswer": "The ability of one object to take many forms",
      "explanation": "\"The ability of one object to take many forms\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_7_q02",
      "lessonId": "oop_lesson_7",
      "question": "Which OOP principle allows one interface to have multiple implementations?",
      "options": [
        "Encapsulation",
        "Inheritance",
        "Polymorphism",
        "Abstraction"
      ],
      "correctAnswer": "Polymorphism",
      "explanation": "\"Polymorphism\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_7_q03",
      "lessonId": "oop_lesson_7",
      "question": "Runtime polymorphism in Java is achieved through:",
      "options": [
        "Constructor Overloading",
        "Method Overloading",
        "Method Overriding",
        "Interfaces only"
      ],
      "correctAnswer": "Method Overriding",
      "explanation": "\"Method Overriding\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_7_q04",
      "lessonId": "oop_lesson_7",
      "question": "Which keyword is commonly used when overriding a method?",
      "options": [
        "@Override",
        "@Inherited",
        "@Method",
        "@Polymorphism"
      ],
      "correctAnswer": "@Override",
      "explanation": "\"@Override\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_7_q05",
      "lessonId": "oop_lesson_7",
      "question": "What is method overriding?",
      "options": [
        "Defining multiple methods with the same name in one class",
        "Redefining a parent class method in the child class",
        "Calling multiple methods at once",
        "Creating multiple constructors"
      ],
      "correctAnswer": "Redefining a parent class method in the child class",
      "explanation": "\"Redefining a parent class method in the child class\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_7_q06",
      "lessonId": "oop_lesson_7",
      "question": "Which of the following is required for runtime polymorphism?",
      "options": [
        "Static methods",
        "Method Overriding",
        "Constructor Overloading",
        "Private variables"
      ],
      "correctAnswer": "Method Overriding",
      "explanation": "\"Method Overriding\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_7_q07",
      "lessonId": "oop_lesson_7",
      "question": "What is the output?",
      "options": [
        "Bird Flying",
        "Eagle Soaring",
        "Error",
        "null"
      ],
      "correctAnswer": "Eagle Soaring",
      "explanation": "\"Eagle Soaring\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "class Bird{\n    void fly(){\n        System.out.println(\"Bird Flying\");\n    }\n}\nclass Eagle extends Bird{\n    @Override\n    void fly(){\n        System.out.println(\"Eagle Soaring\");\n    }\n}\npublic class Main{\n    public static void main(String[] args){\n        Bird b = new Eagle();\n        b.fly();\n    }\n}"
    },
    {
      "id": "oop_lesson_7_q08",
      "lessonId": "oop_lesson_7",
      "question": "Which statement is FALSE?",
      "options": [
        "Polymorphism increases flexibility.",
        "Method overriding supports runtime polymorphism.",
        "Polymorphism requires inheritance.",
        "Constructors can be overridden."
      ],
      "correctAnswer": "Constructors can be overridden.",
      "explanation": "\"Constructors can be overridden.\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_7_q09",
      "lessonId": "oop_lesson_7",
      "question": "Which relationship is commonly used in polymorphism?",
      "options": [
        "Parent class reference → Child object",
        "Child class reference → Parent object",
        "Object → Package",
        "Constructor → Method"
      ],
      "correctAnswer": "Parent class reference → Child object",
      "explanation": "\"Parent class reference → Child object\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_7_q10",
      "lessonId": "oop_lesson_7",
      "question": "What does @Override indicate?",
      "options": [
        "The method replaces an inherited method.",
        "The constructor is overloaded.",
        "The variable is private.",
        "The class is abstract."
      ],
      "correctAnswer": "The method replaces an inherited method.",
      "explanation": "\"The method replaces an inherited method.\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_7_q11",
      "lessonId": "oop_lesson_7",
      "question": "Which of the following demonstrates polymorphic behavior?",
      "options": [
        "Constructor Overloading",
        "Method Overloading",
        "Runtime Polymorphism",
        "Encapsulation"
      ],
      "correctAnswer": "Runtime Polymorphism",
      "explanation": "\"Runtime Polymorphism\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Hard",
      "codeSnippet": "Animal pet = new Dog();\npet.sound();"
    },
    {
      "id": "oop_lesson_7_q12",
      "lessonId": "oop_lesson_7",
      "question": "What is dynamic method dispatch?",
      "options": [
        "Choosing the overridden method during runtime.",
        "Creating multiple objects.",
        "Calling constructors.",
        "Hiding variables."
      ],
      "correctAnswer": "Choosing the overridden method during runtime.",
      "explanation": "\"Choosing the overridden method during runtime.\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_7_q13",
      "lessonId": "oop_lesson_7",
      "question": "Which statement is TRUE about polymorphic references?",
      "options": [
        "A parent reference can refer to a child object.",
        "A child reference can always refer to a parent object without casting.",
        "A constructor can become polymorphic.",
        "Only interfaces support polymorphism."
      ],
      "correctAnswer": "A parent reference can refer to a child object.",
      "explanation": "\"A parent reference can refer to a child object.\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_7_q14",
      "lessonId": "oop_lesson_7",
      "question": "Why is polymorphism useful?",
      "options": [
        "It reduces code flexibility.",
        "It allows reusable and extensible code.",
        "It replaces inheritance.",
        "It prevents method overriding."
      ],
      "correctAnswer": "It allows reusable and extensible code.",
      "explanation": "\"It allows reusable and extensible code.\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_7_q15",
      "lessonId": "oop_lesson_7",
      "question": "A graphics program has classes Circle, Rectangle, and Triangle, each with a draw() method. The program stores them in a list of Shape references and calls draw() on each object. Which OOP concept makes this possible?",
      "options": [
        "Encapsulation",
        "Constructor Overloading",
        "Polymorphism",
        "Enumeration"
      ],
      "correctAnswer": "Polymorphism",
      "explanation": "\"Polymorphism\" is the correct answer based on Topic 7 concepts.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_8": [
    {
      "id": "oop_lesson_8_q01",
      "lessonId": "oop_lesson_8",
      "question": "What is abstraction in Java?",
      "options": [
        "Hiding implementation details while showing only essential features",
        "Creating multiple objects",
        "Hiding variables using private",
        "Creating constructors"
      ],
      "correctAnswer": "Hiding implementation details while showing only essential features",
      "explanation": "\"Hiding implementation details while showing only essential features\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_8_q02",
      "lessonId": "oop_lesson_8",
      "question": "Which keyword is used to declare an abstract class?",
      "options": [
        "interface",
        "public",
        "abstract",
        "extends"
      ],
      "correctAnswer": "abstract",
      "explanation": "\"abstract\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_8_q03",
      "lessonId": "oop_lesson_8",
      "question": "Which statement best describes an abstract class?",
      "options": [
        "It can only contain variables.",
        "It cannot contain methods.",
        "It cannot be instantiated directly.",
        "It is automatically an interface."
      ],
      "correctAnswer": "It cannot be instantiated directly.",
      "explanation": "\"It cannot be instantiated directly.\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_8_q04",
      "lessonId": "oop_lesson_8",
      "question": "Which of the following correctly declares an abstract class?",
      "options": [
        "class Animal{\n}",
        "abstract class Animal{\n}",
        "interface Animal{\n}",
        "public Animal{\n}"
      ],
      "correctAnswer": "abstract class Animal{\n}",
      "explanation": "\"abstract class Animal{\n}\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_8_q05",
      "lessonId": "oop_lesson_8",
      "question": "What is an abstract method?",
      "options": [
        "A method with no body that must be implemented by subclasses",
        "A method with a constructor",
        "A static method",
        "A private method"
      ],
      "correctAnswer": "A method with no body that must be implemented by subclasses",
      "explanation": "\"A method with no body that must be implemented by subclasses\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_8_q06",
      "lessonId": "oop_lesson_8",
      "question": "What is the output?",
      "options": [
        "Animal",
        "Bark",
        "Dog",
        "Error"
      ],
      "correctAnswer": "Bark",
      "explanation": "\"Bark\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "abstract class Animal{\n    abstract void sound();\n}\nclass Dog extends Animal{\n    void sound(){\n        System.out.println(\"Bark\");\n    }\n}\npublic class Main{\n    public static void main(String[] args){\n        Animal a = new Dog();\n        a.sound();\n    }\n}"
    },
    {
      "id": "oop_lesson_8_q07",
      "lessonId": "oop_lesson_8",
      "question": "Which class must implement the abstract methods?",
      "options": [
        "Parent class",
        "Child class",
        "Main class",
        "Package class"
      ],
      "correctAnswer": "Child class",
      "explanation": "\"Child class\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_8_q08",
      "lessonId": "oop_lesson_8",
      "question": "Why are abstract classes useful?",
      "options": [
        "They provide a common template for related classes.",
        "They replace constructors.",
        "They eliminate inheritance.",
        "They automatically create objects."
      ],
      "correctAnswer": "They provide a common template for related classes.",
      "explanation": "\"They provide a common template for related classes.\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_8_q09",
      "lessonId": "oop_lesson_8",
      "question": "Which of the following is NOT allowed?",
      "options": [
        "abstract class Shape{}",
        "Shape s = new Shape();",
        "class Circle extends Shape{}",
        "abstract class Animal{\n    abstract void eat();\n}"
      ],
      "correctAnswer": "Shape s = new Shape();",
      "explanation": "\"Shape s = new Shape();\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_8_q10",
      "lessonId": "oop_lesson_8",
      "question": "Which keyword allows a class to inherit an abstract class?",
      "options": [
        "implements",
        "extends",
        "abstract",
        "super"
      ],
      "correctAnswer": "extends",
      "explanation": "\"extends\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_8_q11",
      "lessonId": "oop_lesson_8",
      "question": "Which real-world example best demonstrates abstraction using an abstract class?",
      "options": [
        "An abstract Employee class with subclasses Teacher and Programmer",
        "A single Student class",
        "An enum for months",
        "A static utility class"
      ],
      "correctAnswer": "An abstract Employee class with subclasses Teacher and Programmer",
      "explanation": "\"An abstract Employee class with subclasses Teacher and Programmer\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_8_q12",
      "lessonId": "oop_lesson_8",
      "question": "What is the output?",
      "options": [
        "Shape",
        "Circle",
        "Error",
        "null"
      ],
      "correctAnswer": "Circle",
      "explanation": "\"Circle\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Hard",
      "codeSnippet": "abstract class Shape{\n    abstract void draw();\n}\nclass Circle extends Shape{\n    void draw(){\n        System.out.println(\"Circle\");\n    }\n}\npublic class Main{\n    public static void main(String[] args){\n        Shape s = new Circle();\n        s.draw();\n    }\n}"
    },
    {
      "id": "oop_lesson_8_q13",
      "lessonId": "oop_lesson_8",
      "question": "Which statement best distinguishes an abstract class from a regular class?",
      "options": [
        "An abstract class cannot have variables.",
        "An abstract class may contain abstract methods and cannot be instantiated directly.",
        "An abstract class cannot extend another class.",
        "An abstract class cannot contain implemented methods."
      ],
      "correctAnswer": "An abstract class may contain abstract methods and cannot be instantiated directly.",
      "explanation": "\"An abstract class may contain abstract methods and cannot be instantiated directly.\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_8_q14",
      "lessonId": "oop_lesson_8",
      "question": "What is the output of the code?",
      "options": [
        "It can be instantiated.",
        "It must remain abstract.",
        "It becomes an interface.",
        "It cannot contain constructors."
      ],
      "correctAnswer": "It can be instantiated.",
      "explanation": "\"It can be instantiated.\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Hard",
      "codeSnippet": "If a subclass implements every abstract method, what can be done?"
    },
    {
      "id": "oop_lesson_8_q15",
      "lessonId": "oop_lesson_8",
      "question": "A software developer wants every Payment type (CashPayment, CreditCardPayment, GCashPayment) to implement a processPayment() method while sharing common payment details. Which feature is most appropriate?",
      "options": [
        "Constructor Overloading",
        "Abstract Class",
        "Enum",
        "Encapsulation"
      ],
      "correctAnswer": "Abstract Class",
      "explanation": "\"Abstract Class\" is the correct answer based on Topic 8 concepts.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_9": [
    {
      "id": "oop_lesson_9_q01",
      "lessonId": "oop_lesson_9",
      "question": "What is an interface in Java?",
      "options": [
        "A special class used to create objects directly",
        "A blueprint that defines methods a class must implement",
        "A constructor with multiple parameters",
        "A package in Java"
      ],
      "correctAnswer": "A blueprint that defines methods a class must implement",
      "explanation": "\"A blueprint that defines methods a class must implement\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_9_q02",
      "lessonId": "oop_lesson_9",
      "question": "Which keyword is used to declare an interface?",
      "options": [
        "abstract",
        "class",
        "interface",
        "implements"
      ],
      "correctAnswer": "interface",
      "explanation": "\"interface\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_9_q03",
      "lessonId": "oop_lesson_9",
      "question": "Which keyword is used by a class to use an interface?",
      "options": [
        "extends",
        "implements",
        "inherits",
        "super"
      ],
      "correctAnswer": "implements",
      "explanation": "\"implements\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_9_q04",
      "lessonId": "oop_lesson_9",
      "question": "Which of the following correctly declares an interface?",
      "options": [
        "interface Animal{\n    void sound();\n}",
        "class Animal{\n    void sound();\n}",
        "abstract interface Animal{\n}",
        "implements Animal{\n}"
      ],
      "correctAnswer": "interface Animal{\n    void sound();\n}",
      "explanation": "\"interface Animal{\n    void sound();\n}\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_9_q05",
      "lessonId": "oop_lesson_9",
      "question": "Which statement about interface methods is TRUE?",
      "options": [
        "They are private by default.",
        "They are public and abstract by default.",
        "They always have method bodies.",
        "They are protected by default."
      ],
      "correctAnswer": "They are public and abstract by default.",
      "explanation": "\"They are public and abstract by default.\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_9_q06",
      "lessonId": "oop_lesson_9",
      "question": "Which statement is FALSE?",
      "options": [
        "Interfaces can contain abstract methods.",
        "Interfaces can be implemented by classes.",
        "Interfaces can be instantiated directly.",
        "Interfaces promote abstraction."
      ],
      "correctAnswer": "Interfaces can be instantiated directly.",
      "explanation": "\"Interfaces can be instantiated directly.\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_9_q07",
      "lessonId": "oop_lesson_9",
      "question": "What happens if a class implements an interface but does not implement all of its methods?",
      "options": [
        "The program runs normally.",
        "Compilation error unless the class is abstract.",
        "Java automatically creates the missing methods.",
        "Nothing happens."
      ],
      "correctAnswer": "Compilation error unless the class is abstract.",
      "explanation": "\"Compilation error unless the class is abstract.\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_9_q08",
      "lessonId": "oop_lesson_9",
      "question": "Which keyword is used to create an object of a class that implements an interface?",
      "options": [
        "implements",
        "interface",
        "new",
        "abstract"
      ],
      "correctAnswer": "new",
      "explanation": "\"new\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_9_q09",
      "lessonId": "oop_lesson_9",
      "question": "Which statement best describes an interface?",
      "options": [
        "It defines what a class should do, not how it does it.",
        "It stores object data.",
        "It replaces constructors.",
        "It creates packages."
      ],
      "correctAnswer": "It defines what a class should do, not how it does it.",
      "explanation": "\"It defines what a class should do, not how it does it.\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_9_q10",
      "lessonId": "oop_lesson_9",
      "question": "Which of the following is a valid interface reference?",
      "options": [
        "Vehicle v = new Car();",
        "Car c = new Vehicle();",
        "Vehicle v = new Vehicle();",
        "new Vehicle();"
      ],
      "correctAnswer": "Vehicle v = new Car();",
      "explanation": "\"Vehicle v = new Car();\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "interface Vehicle{\n    void move();\n}\nclass Car implements Vehicle{\n    public void move(){}\n}"
    },
    {
      "id": "oop_lesson_9_q11",
      "lessonId": "oop_lesson_9",
      "question": "Which statement best distinguishes an interface from an abstract class?",
      "options": [
        "Interfaces support multiple implementation, while classes can extend only one class.",
        "Interfaces cannot declare methods.",
        "Interfaces can be instantiated.",
        "Interfaces replace inheritance."
      ],
      "correctAnswer": "Interfaces support multiple implementation, while classes can extend only one class.",
      "explanation": "\"Interfaces support multiple implementation, while classes can extend only one class.\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_9_q12",
      "lessonId": "oop_lesson_9",
      "question": "A Printer interface declares a method print(). Both LaserPrinter and InkjetPrinter implement the interface differently. Which OOP principle is demonstrated?",
      "options": [
        "Constructor Overloading",
        "Enumeration",
        "Abstraction using Interfaces",
        "Data Hiding"
      ],
      "correctAnswer": "Abstraction using Interfaces",
      "explanation": "\"Abstraction using Interfaces\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_9_q13",
      "lessonId": "oop_lesson_9",
      "question": "Which code correctly implements two interfaces?",
      "options": [
        "class Duck implements Flyable, Swimmable{}",
        "class Duck extends Flyable, Swimmable{}",
        "class Duck inherits Flyable, Swimmable{}",
        "class Duck interface Flyable{}"
      ],
      "correctAnswer": "class Duck implements Flyable, Swimmable{}",
      "explanation": "\"class Duck implements Flyable, Swimmable{}\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Hard",
      "codeSnippet": "interface Flyable{}\ninterface Swimmable{}"
    },
    {
      "id": "oop_lesson_9_q14",
      "lessonId": "oop_lesson_9",
      "question": "What happens if you try to create an object directly from an interface?",
      "options": [
        "The object is created successfully.",
        "Java creates a default implementation.",
        "Compilation error occurs.",
        "The interface becomes abstract."
      ],
      "correctAnswer": "Compilation error occurs.",
      "explanation": "\"Compilation error occurs.\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_9_q15",
      "lessonId": "oop_lesson_9",
      "question": "A university system has different payment methods (Cash, CreditCard, GCash) that all provide a pay() method but have different implementations. Which design is most appropriate?",
      "options": [
        "Constructor Overloading",
        "Enum",
        "Interface",
        "Encapsulation"
      ],
      "correctAnswer": "Interface",
      "explanation": "\"Interface\" is the correct answer based on Topic 9 concepts.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_10": [
    {
      "id": "oop_lesson_10_q01",
      "lessonId": "oop_lesson_10",
      "question": "What is an array of objects in Java?",
      "options": [
        "An array that stores primitive data types only",
        "An array that stores references to objects",
        "A method that stores objects",
        "A constructor that creates arrays"
      ],
      "correctAnswer": "An array that stores references to objects",
      "explanation": "\"An array that stores references to objects\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_10_q02",
      "lessonId": "oop_lesson_10",
      "question": "Which statement correctly declares an array of Student objects?",
      "options": [
        "Student student;",
        "Student[] students;",
        "Student students;",
        "Array<Student> students;"
      ],
      "correctAnswer": "Student[] students;",
      "explanation": "\"Student[] students;\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_10_q03",
      "lessonId": "oop_lesson_10",
      "question": "Which statement creates an array that can hold five Student objects?",
      "options": [
        "Student students = new Student(5);",
        "Student[] students = new Student[5];",
        "Student students[] = 5;",
        "new Student();"
      ],
      "correctAnswer": "Student[] students = new Student[5];",
      "explanation": "\"Student[] students = new Student[5];\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_10_q04",
      "lessonId": "oop_lesson_10",
      "question": "What does the following code create?",
      "options": [
        "Three Student objects",
        "An array capable of storing three Student object references",
        "A single Student object",
        "A compilation error"
      ],
      "correctAnswer": "An array capable of storing three Student object references",
      "explanation": "\"An array capable of storing three Student object references\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Easy",
      "codeSnippet": "Student[] students = new Student[3];"
    },
    {
      "id": "oop_lesson_10_q05",
      "lessonId": "oop_lesson_10",
      "question": "Which statement creates the first object in the array?",
      "options": [
        "students = new Student();",
        "students[0] = new Student();",
        "Student[0] = students;",
        "new students[0];"
      ],
      "correctAnswer": "students[0] = new Student();",
      "explanation": "\"students[0] = new Student();\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_10_q06",
      "lessonId": "oop_lesson_10",
      "question": "What happens if you execute this?",
      "options": [
        "Prints null",
        "Compilation Error",
        "NullPointerException",
        "Prints Student"
      ],
      "correctAnswer": "NullPointerException",
      "explanation": "\"NullPointerException\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Medium",
      "codeSnippet": "Student[] students = new Student[2];\nSystem.out.println(students[0].name);"
    },
    {
      "id": "oop_lesson_10_q07",
      "lessonId": "oop_lesson_10",
      "question": "Which statement correctly initializes every element?",
      "options": [
        "for(int i=0;i<students.length;i++){\n    students[i]=new Student();\n}",
        "students = new Student();",
        "Student();",
        "students.new();"
      ],
      "correctAnswer": "for(int i=0;i<students.length;i++){\n    students[i]=new Student();\n}",
      "explanation": "\"for(int i=0;i<students.length;i++){\n    students[i]=new Student();\n}\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_10_q08",
      "lessonId": "oop_lesson_10",
      "question": "What is the index of the first element in an array?",
      "options": [
        "1",
        "-1",
        "0",
        "Depends on the array"
      ],
      "correctAnswer": "0",
      "explanation": "\"0\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_10_q09",
      "lessonId": "oop_lesson_10",
      "question": "What is the index of the last element in an array of length 5?",
      "options": [
        "5",
        "6",
        "4",
        "3"
      ],
      "correctAnswer": "4",
      "explanation": "\"4\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_10_q10",
      "lessonId": "oop_lesson_10",
      "question": "Which property returns the size of an array?",
      "options": [
        "size()",
        "count()",
        "length",
        "getSize()"
      ],
      "correctAnswer": "length",
      "explanation": "\"length\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_10_q11",
      "lessonId": "oop_lesson_10",
      "question": "What exception occurs if you access an index beyond the array size?",
      "options": [
        "NullPointerException",
        "ArithmeticException",
        "ArrayIndexOutOfBoundsException",
        "IOException"
      ],
      "correctAnswer": "ArrayIndexOutOfBoundsException",
      "explanation": "\"ArrayIndexOutOfBoundsException\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_10_q12",
      "lessonId": "oop_lesson_10",
      "question": "Which code correctly creates three Book objects?",
      "options": [
        "Book[] books = new Book[3];\n\nfor(int i=0;i<books.length;i++){\n    books[i]=new Book();\n}",
        "Book books = new Book();",
        "Book[3];",
        "new Book[3];"
      ],
      "correctAnswer": "Book[] books = new Book[3];\n\nfor(int i=0;i<books.length;i++){\n    books[i]=new Book();\n}",
      "explanation": "\"Book[] books = new Book[3];\n\nfor(int i=0;i<books.length;i++){\n    books[i]=new Book();\n}\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_10_q13",
      "lessonId": "oop_lesson_10",
      "question": "Why are arrays of objects useful?",
      "options": [
        "They allow storing multiple related objects efficiently.",
        "They eliminate classes.",
        "They replace methods.",
        "They prevent inheritance."
      ],
      "correctAnswer": "They allow storing multiple related objects efficiently.",
      "explanation": "\"They allow storing multiple related objects efficiently.\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_10_q14",
      "lessonId": "oop_lesson_10",
      "question": "What is printed?",
      "options": [
        "Toyota",
        "Car",
        "null",
        "Error"
      ],
      "correctAnswer": "Toyota",
      "explanation": "\"Toyota\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Hard",
      "codeSnippet": "class Car{\n    String brand=\"Toyota\";\n}\nCar[] cars=new Car[1];\ncars[0]=new Car();\nSystem.out.println(cars[0].brand);"
    },
    {
      "id": "oop_lesson_10_q15",
      "lessonId": "oop_lesson_10",
      "question": "A university wants to store information for 500 students (name, ID, course, and GPA). Which Java feature is the most appropriate?",
      "options": [
        "Array of Objects",
        "Enum",
        "Constructor Overloading",
        "Interface"
      ],
      "correctAnswer": "Array of Objects",
      "explanation": "\"Array of Objects\" is the correct answer based on Topic 10 concepts.",
      "difficulty": "Hard"
    }
  ],
  "oop_lesson_11": [
    {
      "id": "oop_lesson_11_q01",
      "lessonId": "oop_lesson_11",
      "question": "What is an enum in Java?",
      "options": [
        "A class used for inheritance",
        "A special data type used to define a fixed set of constants",
        "A constructor",
        "A method"
      ],
      "correctAnswer": "A special data type used to define a fixed set of constants",
      "explanation": "\"A special data type used to define a fixed set of constants\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_11_q02",
      "lessonId": "oop_lesson_11",
      "question": "Which keyword is used to declare an enum?",
      "options": [
        "class",
        "interface",
        "enum",
        "final"
      ],
      "correctAnswer": "enum",
      "explanation": "\"enum\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_11_q03",
      "lessonId": "oop_lesson_11",
      "question": "Which of the following correctly declares an enum?",
      "options": [
        "enum Day {\n    MONDAY, TUESDAY, WEDNESDAY\n}",
        "class Day {\n    MONDAY, TUESDAY\n}",
        "Enum Day {\n}",
        "constant Day {\n}"
      ],
      "correctAnswer": "enum Day {\n    MONDAY, TUESDAY, WEDNESDAY\n}",
      "explanation": "\"enum Day {\n    MONDAY, TUESDAY, WEDNESDAY\n}\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_11_q04",
      "lessonId": "oop_lesson_11",
      "question": "Which statement is TRUE about enum constants?",
      "options": [
        "They can change at runtime.",
        "They are fixed and predefined.",
        "They must be integers.",
        "They are methods."
      ],
      "correctAnswer": "They are fixed and predefined.",
      "explanation": "\"They are fixed and predefined.\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_11_q05",
      "lessonId": "oop_lesson_11",
      "question": "Which enum declaration is valid?",
      "options": [
        "enum Color{\n    RED, GREEN, BLUE\n}",
        "enum Color{\n    RED GREEN BLUE\n}",
        "Color enum{\n}",
        "class enum Color{\n}"
      ],
      "correctAnswer": "enum Color{\n    RED, GREEN, BLUE\n}",
      "explanation": "\"enum Color{\n    RED, GREEN, BLUE\n}\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Easy"
    },
    {
      "id": "oop_lesson_11_q06",
      "lessonId": "oop_lesson_11",
      "question": "Which statement is FALSE?",
      "options": [
        "Enums can contain methods.",
        "Enums can contain constructors.",
        "New enum constants can be added at runtime.",
        "Enums improve code readability."
      ],
      "correctAnswer": "New enum constants can be added at runtime.",
      "explanation": "\"New enum constants can be added at runtime.\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_11_q07",
      "lessonId": "oop_lesson_11",
      "question": "Which code retrieves all enum constants?",
      "options": [
        "Day.values();",
        "Day.valueOf();",
        "Day.ordinal();",
        "Day.getValues();"
      ],
      "correctAnswer": "Day.values();",
      "explanation": "\"Day.values();\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_11_q08",
      "lessonId": "oop_lesson_11",
      "question": "Which statement converts the string \"RED\" into an enum constant?",
      "options": [
        "Color.valueOf(\"RED\");",
        "Color.values(\"RED\");",
        "new Color(\"RED\");",
        "Color.ordinal(\"RED\");"
      ],
      "correctAnswer": "Color.valueOf(\"RED\");",
      "explanation": "\"Color.valueOf(\"RED\");\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_11_q09",
      "lessonId": "oop_lesson_11",
      "question": "Which statement best describes enums?",
      "options": [
        "They represent a fixed set of related constants.",
        "They replace interfaces.",
        "They create objects.",
        "They overload constructors."
      ],
      "correctAnswer": "They represent a fixed set of related constants.",
      "explanation": "\"They represent a fixed set of related constants.\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_11_q10",
      "lessonId": "oop_lesson_11",
      "question": "Which of the following is a practical use of enums?",
      "options": [
        "Days of the week",
        "Student names",
        "User passwords",
        "Variable input values"
      ],
      "correctAnswer": "Days of the week",
      "explanation": "\"Days of the week\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Medium"
    },
    {
      "id": "oop_lesson_11_q11",
      "lessonId": "oop_lesson_11",
      "question": "Which statement is NOT a good use of an enum?",
      "options": [
        "User Roles",
        "Months of the Year",
        "Traffic Light Colors",
        "Student Ages"
      ],
      "correctAnswer": "Student Ages",
      "explanation": "\"Student Ages\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_11_q12",
      "lessonId": "oop_lesson_11",
      "question": "Which switch statement correctly uses an enum?",
      "options": [
        "switch(day){\n    case MONDAY:\n        System.out.println(\"Start\");\n        break;\n}",
        "switch(enum){\n}",
        "switch(values()){\n}",
        "switch(ordinal()){\n}"
      ],
      "correctAnswer": "switch(day){\n    case MONDAY:\n        System.out.println(\"Start\");\n        break;\n}",
      "explanation": "\"switch(day){\n    case MONDAY:\n        System.out.println(\"Start\");\n        break;\n}\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_11_q13",
      "lessonId": "oop_lesson_11",
      "question": "Which statement is TRUE about enum constructors?",
      "options": [
        "They are always public.",
        "They are implicitly private.",
        "They do not exist.",
        "They must return a value."
      ],
      "correctAnswer": "They are implicitly private.",
      "explanation": "\"They are implicitly private.\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_11_q14",
      "lessonId": "oop_lesson_11",
      "question": "A school system has three student statuses: ENROLLED GRADUATED DROPPED Which Java feature is most appropriate?",
      "options": [
        "Array",
        "Interface",
        "Enum",
        "Constructor"
      ],
      "correctAnswer": "Enum",
      "explanation": "\"Enum\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Hard"
    },
    {
      "id": "oop_lesson_11_q15",
      "lessonId": "oop_lesson_11",
      "question": "A game has four difficulty levels: EASY MEDIUM HARD EXPERT Which Java feature best represents these values?",
      "options": [
        "Class",
        "Interface",
        "Enum",
        "Abstract Class"
      ],
      "correctAnswer": "Enum",
      "explanation": "\"Enum\" is the correct answer based on Topic 11 concepts.",
      "difficulty": "Hard"
    }
  ]
};
